version: "3.8"

services:
  zest:
    container_name: zest
    image: maximofn/zest:1.0.1
    build: .
    runtime: nvidia
    network_mode: "host"
    volumes:
      - ./hub:/root/.cache/huggingface/hub
    tty: true
    stdin_open: true
